name: web3_in_flutter
description: 'Web3 In Flutter'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web3dart: ^2.7.3
  http: ^1.6.0
  reown_appkit: ^1.7.4
  flutter_dotenv: ^6.0.0
  solana: ^0.32.0
  millisecs: ^0.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
